[create_session]
cla = "NO_SM_CLA"
ins = "INS_MGMT"
p1 = "P1_DEFAULT"
p2 = "P2_DEFAULT"
le = 0x0C
contains_arbitrary_payload = false
contains_arbitrary_response = false

[create_session.payload]
TAG_1 = { name = "object_id", type = "ObjectId"}

[create_session.response]
TAG_1 = { name = "session_id", type = "SessionId"}


[exchange_session_data]
cla = "NO_SM_CLA"
ins = "INS_MGMT"
p1 = "P1_DEFAULT"
p2 = "P2_SESSION_POLICY"
le = 0x00

[exchange_session_data.payload]
TAG_1 = { name = "session_policy", type = "SessionPolicy"}
then = { name = "c_mac", type = "&'data [u8]"}

[exchange_session_data.response]
then = { name = "r_mac", type = "&'data [u8]"}


[get_random]
cla = "NO_SM_CLA"
ins = "INS_MGMT"
p1 = "P1_DEFAULT"
p2 = "P2_RANDOM"
le = "ExpectedLen::Max"
contains_arbitrary_payload = false

[get_random.payload]
TAG_1 = { name = "length", type = "Be<u16>" }

[get_random.response]
TAG_1 = { name = "data", type = "&'data [u8]" }
